@ApiURL = http://localhost:5128

GET {{ApiURL}}/people
Accept: application/json

###


POST {{ApiURL}}/people
Content-Type: application/json

{
  "name": "John",
  "email": "{{$random.email}}",
  "document": "01232044024"
}