# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  push_to_registry:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ismael3s/citynexus.people:latest
            ismael3s/citynexus.people:${{ steps.vars.outputs.sha_short }}
          context: .
          file: ./src/CityNexus.People.Api/Dockerfile
  update_k8s:
    permissions:
      contents: write
    needs: push_to_registry
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ismael3s/citynexus.people:${{ needs.push_to_registry.outputs.sha_short }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ismael3s/CityNexus.K8S
          persist-credentials: false
          fetch-depth: 0
      - name: Update Image Deployment
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.13.5/yq_darwin_amd64.tar.gz -O yq_darwin_amd64.tar.gz && tar -xvf yq_darwin_amd64.tar.gz && chmod +x yq_darwin_amd64 && mv yq_darwin_amd64 yq
          yq e '.spec.template.spec.containers[0].image = env(DOCKER_IMAGE)' -i CityNexus.People/deployment.yml
          rm -f yq yq.1 install-man-page.sh yq_darwin_amd64.tar.gz
      - name: Commit and push the changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          branch: main
          repository: ismael3s/CityNexus.K8S
          message: "Update CityNexus.People image to $DOCKER_IMAGE"
